api_platform:
    title: "Timelogger API"
    description: "API used to log students' activity in the cluster"
    version: "1.3.6"
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
